title: Luis Perez
logo: website_materials/assets/img/JMpic2.png
description: I am a PhD candidate in Economics at the University of Minnesota. I am in the 2023/24 Job Market, and will be available for interviews at the EEA and ASSA meetings.
#show_dowloads: true
theme: jekyll-theme-minimal
